/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_ltbILGc2x",
    "aws_user_pools_web_client_id": "6e6soq7mrlip6mmsb9kcmp72k3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://n7nnbxlm3fgmrp4vlqo3zt2gce.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
